version: '3'
services:
    nginx:
        depends_on:
            - trello
        image: bbq923/bbqnginx
        links:
            - trello:app
        ports:
            - "80:80"
    trello:
        image: bbq923/bbqtrello-docker
        links:
            - db:bbqmysql
        volumes:
            - ./trellobase:/trellobase
    db:
        image: mysql
        ports:
            - target : 3306
              published : 8000
              protocol : tcp
              mode : host
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_USER: bbq923
            MYSQL_PASSWORD: 123456
            MYSQL_DATABASE: trellobase
volumes:
    trellobase: